/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import proyecto.entities.Report;
import proyecto.entities.User;
import proyecto.utils.Colors;
import proyecto.utils.RoundedLineBorder;
import proyecto.utils.SetImageLabel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import proyecto.db.Caller;
/**
 *
 * @author juan
 */
public class WelcomeView extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form ReportGeneration
     */
    public WelcomeView(User user) throws SQLException {
        this.user = user;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        generateReportLabel4 = new javax.swing.JLabel();
        closeAppButton = new javax.swing.JButton();
        viewReportsButton = new javax.swing.JButton();
        createReportButton = new javax.swing.JButton();
        createReportLabel = new javax.swing.JLabel();
        viewReportsLabel = new javax.swing.JLabel();
        closeAppLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        generateReportLabel3 = new javax.swing.JLabel();
        generateReportLabel = new javax.swing.JLabel();
        generateReportLabel1 = new javax.swing.JLabel();
        logOutIconButton = new javax.swing.JButton();
        logOutIcon = new javax.swing.JLabel();
        profileIconButton = new javax.swing.JButton();
        profileIcon = new javax.swing.JLabel();
        creamContainer = new javax.swing.JLabel();
        waveBg = new javax.swing.JLabel();
        BlueBackGround = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(961, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userLabel.setForeground(Colors.darkBlue);
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Bienvenido "+user.getName());
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 440, -1));

        generateReportLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        generateReportLabel4.setForeground(Colors.darkBlue);
        generateReportLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateReportLabel4.setText("¿Qué desea hacer?");
        getContentPane().add(generateReportLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 470, -1));

        closeAppButton.setBackground(Colors.darkBlue);
        closeAppButton.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        closeAppButton.setForeground(Colors.creamWhiteText);
        closeAppButton.setText("Cerrar programa");
        closeAppButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 100, 2, 14));
        closeAppButton.setContentAreaFilled(false);
        closeAppButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeAppButton.setFocusable(false);
        closeAppButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        closeAppButton.setMargin(new java.awt.Insets(2, 100, 2, 14));
        closeAppButton.setMaximumSize(new java.awt.Dimension(135, 36));
        closeAppButton.setMinimumSize(new java.awt.Dimension(135, 36));
        closeAppButton.setPreferredSize(new java.awt.Dimension(340, 75));
        closeAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAppButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeAppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        viewReportsButton.setBackground(Colors.darkBlue);
        viewReportsButton.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        viewReportsButton.setForeground(Colors.creamWhiteText);
        viewReportsButton.setText("Ver reportes");
        viewReportsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 100, 2, 14));
        viewReportsButton.setContentAreaFilled(false);
        viewReportsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewReportsButton.setFocusable(false);
        viewReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewReportsButton.setMargin(new java.awt.Insets(2, 100, 2, 14));
        viewReportsButton.setMaximumSize(new java.awt.Dimension(135, 36));
        viewReportsButton.setMinimumSize(new java.awt.Dimension(135, 36));
        viewReportsButton.setPreferredSize(new java.awt.Dimension(340, 75));
        viewReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        createReportButton.setBackground(Colors.darkBlue);
        createReportButton.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        createReportButton.setForeground(Colors.creamWhiteText);
        createReportButton.setText("Crear un reporte");
        createReportButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 100, 2, 14));
        createReportButton.setContentAreaFilled(false);
        createReportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createReportButton.setFocusPainted(false);
        createReportButton.setFocusable(false);
        createReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createReportButton.setMargin(new java.awt.Insets(2, 100, 2, 14));
        createReportButton.setMaximumSize(new java.awt.Dimension(135, 36));
        createReportButton.setMinimumSize(new java.awt.Dimension(135, 36));
        createReportButton.setPreferredSize(new java.awt.Dimension(340, 75));
        createReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        createReportLabel.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        createReportLabel.setForeground(Colors.darkBlue);
        createReportLabel.setPreferredSize(new java.awt.Dimension(340, 75));
        createReportLabel.setSize(new java.awt.Dimension(340, 75));
        new SetImageLabel().SetImage(createReportLabel, "/resources/penBar.png");
        getContentPane().add(createReportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        viewReportsLabel.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        viewReportsLabel.setForeground(Colors.darkBlue);
        viewReportsLabel.setOpaque(true);
        viewReportsLabel.setPreferredSize(new java.awt.Dimension(340, 75));
        viewReportsLabel.setSize(new java.awt.Dimension(340, 75));
        new SetImageLabel().SetImage(viewReportsLabel, "/resources/magBar.png");
        getContentPane().add(viewReportsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        closeAppLabel.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        closeAppLabel.setForeground(Colors.darkBlue);
        closeAppLabel.setOpaque(true);
        closeAppLabel.setPreferredSize(new java.awt.Dimension(340, 75));
        closeAppLabel.setSize(new java.awt.Dimension(340, 75));
        new SetImageLabel().SetImage(closeAppLabel, "/resources/powBar.png");
        getContentPane().add(closeAppLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        logoLabel.setText("jLabel1");
        logoLabel.setPreferredSize(new java.awt.Dimension(393, 256));
        logoLabel.setSize(new java.awt.Dimension(393, 256));
        new SetImageLabel().SetImage(logoLabel,"/resources/nobgicon.png");
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        generateReportLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        generateReportLabel3.setForeground(Colors.creamWhiteText);
        generateReportLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateReportLabel3.setText("CargoMara C.A");
        generateReportLabel3.setPreferredSize(new java.awt.Dimension(280, 29));
        getContentPane().add(generateReportLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 280, 50));

        generateReportLabel.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        generateReportLabel.setForeground(Colors.creamWhiteText);
        generateReportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateReportLabel.setText("Sistema de gestión de");
        generateReportLabel.setPreferredSize(new java.awt.Dimension(280, 29));
        getContentPane().add(generateReportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 280, -1));

        generateReportLabel1.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        generateReportLabel1.setForeground(Colors.creamWhiteText);
        generateReportLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateReportLabel1.setText("reportes de incidencias");
        generateReportLabel1.setPreferredSize(new java.awt.Dimension(280, 29));
        getContentPane().add(generateReportLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        logOutIconButton.setBorderPainted(false);
        logOutIconButton.setContentAreaFilled(false);
        logOutIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutIconButton.setFocusable(false);
        logOutIconButton.setPreferredSize(new java.awt.Dimension(70, 84));
        logOutIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutIconButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        logOutIcon.setPreferredSize(new java.awt.Dimension(70, 84));
        logOutIcon.setSize(70,84);
        new SetImageLabel().SetImage(logOutIcon, "/resources/LogOut.png");
        getContentPane().add(logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        profileIconButton.setBorderPainted(false);
        profileIconButton.setContentAreaFilled(false);
        profileIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileIconButton.setFocusable(false);
        profileIconButton.setPreferredSize(new java.awt.Dimension(70, 84));
        profileIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profileIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        profileIcon.setPreferredSize(new java.awt.Dimension(70, 84));
        profileIcon.setSize(70,84);
        new SetImageLabel().SetImage(profileIcon, "/resources/EditProfile.png");
        getContentPane().add(profileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        creamContainer.setBackground(Colors.creamWhite);
        creamContainer.setBorder(new RoundedLineBorder(Colors.creamWhite, 1, 50, true));
        creamContainer.setPreferredSize(new java.awt.Dimension(444, 360));
        getContentPane().add(creamContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 130, 470, -1));

        waveBg.setPreferredSize(new java.awt.Dimension(961, 540));
        waveBg.setSize(new Dimension(961,540));
        new SetImageLabel().SetImage(waveBg, "/resources/BgBig.png");
        getContentPane().add(waveBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BlueBackGround.setBackground(Colors.darkBlue);
        BlueBackGround.setPreferredSize(new java.awt.Dimension(961, 540));

        javax.swing.GroupLayout BlueBackGroundLayout = new javax.swing.GroupLayout(BlueBackGround);
        BlueBackGround.setLayout(BlueBackGroundLayout);
        BlueBackGroundLayout.setHorizontalGroup(
            BlueBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
        );
        BlueBackGroundLayout.setVerticalGroup(
            BlueBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(BlueBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileIconButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_profileIconButtonActionPerformed
        dispose();
        try {
            new EditProfile(user).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(WelcomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_profileIconButtonActionPerformed

    private void logOutIconButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_logOutIconButtonActionPerformed
        dispose();
        new Login().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_logOutIconButtonActionPerformed

    private void createReportButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_createReportButtonActionPerformed
        dispose();
        try {
            new ReportGeneration(user).setVisible(true); // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(WelcomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createReportButtonActionPerformed

    private void closeAppButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeAppButtonActionPerformed
        dispose();
        
    }//GEN-LAST:event_closeAppButtonActionPerformed

    private void viewReportsButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_viewReportsButtonActionPerformed
        dispose();
        try {
            new ReportList(user).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(WelcomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewReportsButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BlueBackGround;
    public javax.swing.JButton closeAppButton;
    public javax.swing.JLabel closeAppLabel;
    public javax.swing.JLabel creamContainer;
    public javax.swing.JButton createReportButton;
    public javax.swing.JLabel createReportLabel;
    public javax.swing.JLabel generateReportLabel;
    public javax.swing.JLabel generateReportLabel1;
    public javax.swing.JLabel generateReportLabel3;
    public javax.swing.JLabel generateReportLabel4;
    public javax.swing.JLabel logOutIcon;
    public javax.swing.JButton logOutIconButton;
    public javax.swing.JLabel logoLabel;
    public javax.swing.JLabel profileIcon;
    public javax.swing.JButton profileIconButton;
    public javax.swing.JLabel userLabel;
    public javax.swing.JButton viewReportsButton;
    public javax.swing.JLabel viewReportsLabel;
    public javax.swing.JLabel waveBg;
    // End of variables declaration//GEN-END:variables
}
