/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.views;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import proyecto.entities.User;
import proyecto.utils.Colors;
import proyecto.utils.RoundedLineBorder;
import proyecto.utils.SetImageLabel;

/**
 *
 * @author juan
 */
public class ReportList1 extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form ReportGeneration
     */
    public ReportList1(User user) {
        this.user = user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        generateReportLabel = new javax.swing.JLabel();
        generateReportLabel2 = new javax.swing.JLabel();
        logOutIconButton = new javax.swing.JButton();
        logOutIcon = new javax.swing.JLabel();
        profileIconButton = new javax.swing.JButton();
        profileIcon = new javax.swing.JLabel();
        logoPicButton = new javax.swing.JButton();
        logoPic = new javax.swing.JLabel();
        creamContainer = new javax.swing.JLabel();
        BlueBackGround = new javax.swing.JPanel();
        waveBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar Reporte");
        setResizable(false);
        setSize(new java.awt.Dimension(961, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(Colors.creamWhiteText);
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(Colors.darkBlue);

        jTable1.setBackground(Colors.creamWhiteText);
        jTable1.setForeground(Colors.darkBlue);
        jTable1.setModel(new javax.swing.table.DefaultTableModel()
        );
        DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addColumn("Fecha de envío");
        model.addColumn("Tipo de reporte");
        model.addColumn("Título del reporte");
        model.addColumn("Estado");
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AAAA"});
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AABAA"});
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AABAA"});
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AAAA"});
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AACAA"});
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AADAA"});
        model.addRow(new Object[] {"TEST1","TEST1","TEST1","AAADA"});
        jTable1.setGridColor(Colors.darkBlue);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setForeground(Colors.darkBlue);
        jTable1.getTableHeader().setBackground(Colors.creamWhiteText);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.getViewport().setBackground(Colors.creamWhiteText);
        jScrollPane1.getViewport().setOpaque(true);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 170));

        generateReportLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        generateReportLabel.setForeground(Colors.darkBlue);
        generateReportLabel.setText("Seleccione un reporte para ver sus detalles");
        getContentPane().add(generateReportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        generateReportLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        generateReportLabel2.setForeground(Colors.darkBlue);
        generateReportLabel2.setText("Reportes Recibidos");
        getContentPane().add(generateReportLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 20));

        logOutIconButton.setBorderPainted(false);
        logOutIconButton.setContentAreaFilled(false);
        logOutIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutIconButton.setFocusable(false);
        logOutIconButton.setPreferredSize(new java.awt.Dimension(70, 84));
        logOutIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutIconButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        logOutIcon.setPreferredSize(new java.awt.Dimension(70, 84));
        logOutIcon.setSize(70,84);
        new SetImageLabel().SetImage(logOutIcon, "/resources/LogOut.png");
        getContentPane().add(logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        profileIconButton.setBorderPainted(false);
        profileIconButton.setContentAreaFilled(false);
        profileIconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileIconButton.setFocusable(false);
        profileIconButton.setPreferredSize(new java.awt.Dimension(70, 84));
        profileIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profileIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        profileIcon.setPreferredSize(new java.awt.Dimension(70, 84));
        profileIcon.setSize(70,84);
        new SetImageLabel().SetImage(profileIcon, "/resources/EditProfile.png");
        getContentPane().add(profileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        logoPicButton.setBackground(new java.awt.Color(255, 153, 0, 0));
        logoPicButton.setBorderPainted(false);
        logoPicButton.setContentAreaFilled(false);
        logoPicButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoPicButton.setFocusable(false);
        logoPicButton.setPreferredSize(new java.awt.Dimension(375, 130));
        logoPicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoPicButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoPicButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        logoPic.setPreferredSize(new java.awt.Dimension(375, 130));
        logoPic.setSize(375, 130);
        new SetImageLabel().SetImage(logoPic, "/resources/Logo3.png");
        getContentPane().add(logoPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        creamContainer.setBackground(Colors.creamWhite);
        creamContainer.setBorder(new RoundedLineBorder(Colors.creamWhite, 1, 50, true));
        creamContainer.setPreferredSize(new java.awt.Dimension(884, 346));
        getContentPane().add(creamContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 135, -1, -1));

        BlueBackGround.setBackground(Colors.darkBlue);
        BlueBackGround.setPreferredSize(new java.awt.Dimension(961, 540));

        waveBg.setPreferredSize(new java.awt.Dimension(961, 540));
        waveBg.setSize(new Dimension(961,540));
        new SetImageLabel().SetImage(waveBg, "/resources/BgBig.png");

        javax.swing.GroupLayout BlueBackGroundLayout = new javax.swing.GroupLayout(BlueBackGround);
        BlueBackGround.setLayout(BlueBackGroundLayout);
        BlueBackGroundLayout.setHorizontalGroup(
            BlueBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlueBackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waveBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BlueBackGroundLayout.setVerticalGroup(
            BlueBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlueBackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waveBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(BlueBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoPicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoPicButtonActionPerformed
        dispose();
        try {
            new WelcomeView(user).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportList1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoPicButtonActionPerformed

    private void profileIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileIconButtonActionPerformed
        dispose();
        try {
            new EditProfile(user).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportList1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_profileIconButtonActionPerformed

    private void logOutIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutIconButtonActionPerformed
        dispose();
        new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_logOutIconButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlueBackGround;
    private javax.swing.JLabel creamContainer;
    private javax.swing.JLabel generateReportLabel;
    private javax.swing.JLabel generateReportLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logOutIcon;
    private javax.swing.JButton logOutIconButton;
    private javax.swing.JLabel logoPic;
    private javax.swing.JButton logoPicButton;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JButton profileIconButton;
    private javax.swing.JLabel waveBg;
    // End of variables declaration//GEN-END:variables
}
